### ISSUE TITLE
HTTPS request fails and `import ssl` doesn't work

### ISSUE THREAD

**Issue by takaakifuji** [schriftgestalt/GlyphsPythonPlugin#2]
Fails when I install the Python 3.9 environment via Plugin Manager and try to fetch data with `urllib.request.urlopen()`:

```py
Traceback (most recent call last):
  File "<macro panel>", line 3
  File "request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "request.py", line 517, in open
    response = self._open(req, data)
  File "request.py", line 539, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "request.py", line 494, in _call_chain
    result = func(*args)
  File "request.py", line 1413, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
```

Then I get the following if I run `import ssl` for troubleshoot:

```py
Traceback (most recent call last):
  File "<macro panel>", line 1
  File "ssl.py", line 98
    import _ssl             # if we can't import it, let the error propagate
ImportError: dlopen(/Users/tfuji/Library/Application Support/Glyphs 3/Repositories/GlyphsPythonPlugin/Python.framework/Versions/3.9/lib/python3.9/lib-dynload/_ssl.cpython-39-darwin.so, 2): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.9/lib/libssl.1.1.dylib
  Referenced from: /Users/tfuji/Library/Application Support/Glyphs 3/Repositories/GlyphsPythonPlugin/Python.framework/Versions/3.9/lib/python3.9/lib-dynload/_ssl.cpython-39-darwin.so
  Reason: image not found
```

Some of the Mach-O executables inside `Python.framework` look for their dependencies inside `/Library/Frameworks/Python.framework/Versions/3.9`, which doesn't exist on my Mac, according to `$ otool -L`:

```
/Users/tfuji/Library/Application Support/Glyphs 3/Repositories/GlyphsPythonPlugin/Python.framework/Versions/3.9/lib/python3.9/lib-dynload/_ssl.cpython-39-darwin.so:
	/Library/Frameworks/Python.framework/Versions/3.9/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/Library/Frameworks/Python.framework/Versions/3.9/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
```

Manually fixing things around with `otool` and `install_name_tool` and re-signing the framework did solve the dyld issue for me. All the dependencies are already contained in the framework, so the linkage to a file under `/Library/Frameworks` looks accidental. I also needed to tweak a bit to make sure that the CA bundle can be found by default:

```py
import ssl
import functools
import pip._vendor.certifi as certifi
ssl._create_default_https_context = functools.partial(ssl.create_default_context, cafile=certifi.where())

from urllib.request import urlopen
print(urlopen('https://github.com/schriftgestalt/GlyphsSDK/raw/Glyphs3/README.md').read().decode('utf-8'))
```

It worked. I have almost zero experience on py2app, but I think the py2app-based build script is supposed to do this for us. If we can make the build right, `urlopen()` should just start to work without [making a request via PyObjC](https://forum.glyphsapp.com/t/the-python-module-cant-handle-https-with-urllib-request/19035/5) instead.

See also: https://bugs.python.org/issue42514

**Comment by schriftgestalt** [comment]
Thanks.
Could you post the commands you used to change the loader paths? And what you "tweaked". Then I could fix that for the next release.

**Comment by takaakifuji** [comment]
Thanks. I prepared [a shell script as a gist](https://gist.github.com/takaakifuji/da7cd6131cd0748d9ce67482f1ed0245) I used to fix the framework but in the end I could not eliminate the absolute `@rpath` to make it work, which is crucial to make the framework truly relocatable. But anyway, try the following commands:

```sh
$ ./fix_python_framework_paths.sh "$HOME/Library/Application Support/Glyphs 3/Repositories/GlyphsPythonPlugin/Python.framework"
$ codesign --sign '<your-identity>' -vvvv --force --strict --timestamp --deep --option=runtime --preserve-metadata=identifier,entitlements,requirements,runtime "$HOME/Library/Application Support/Glyphs 3/Repositories/GlyphsPythonPlugin/Python.framework"
```
Before executing any Python scripts in Glyphs, evaluating the line
```ssl._create_default_https_context = functools.partial(ssl.create_default_context, cafile=certifi.where())```
will let Python resolve the root certificates using the CA bundle in the pip package. Not sure if it's optimal though.

Tested on macOS 10.15.7 and Glyphs 3.1.1 (3146).

**Comment by takaakifuji** [comment]
After some experiments I think I've successfully eliminated the user-specific absolute `@rpath` with [this revision of the gist](https://gist.github.com/takaakifuji/da7cd6131cd0748d9ce67482f1ed0245/d62142d201c119a5e35d9571e0c6ff1602e879b3) and now the paths will be resolved relatively based on `@loader_path`. Have a look at the gist when you have time.
